# -*- coding: utf-8 -*-
"""Aplana la salida de build_library.py a archivos planos y regenera las reglas de Netlify.
Flattens build_library.py output (guias/x/index.html) into flat files (guias-x.html) and
regenerates the "BEGIN LIBRARY" block of netlify.toml with 200 rewrites only.

Why no "/x -> /x/" 301 rules: Netlify matches redirect rules with or without the trailing
slash, so such a rule redirects /x/ to itself forever (this broke the site in Sept 2026).
The no-slash URL is sent to the slash URL by a small script in each page (tools/post/add-slash.js).

Usage (repo root): python tools/flatten.py
"""
import os, re, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOP = ["guias", "glosario", "preguntas-frecuentes", "herramientas", os.path.join("en", "guides"),
       os.path.join("en", "glossary"), os.path.join("en", "faq"), os.path.join("en", "tools")]

pages = []  # (url path, flat file)
for top in TOP:
    base = os.path.join(ROOT, top)
    if not os.path.isdir(base):
        continue
    for dirpath, _, files in os.walk(base):
        if "index.html" not in files:
            continue
        rel = os.path.relpath(dirpath, ROOT).replace(os.sep, "/")
        flat = rel.replace("/", "-") + ".html"
        shutil.copyfile(os.path.join(dirpath, "index.html"), os.path.join(ROOT, flat))
        pages.append(("/" + rel + "/", flat))
for top in ["guias", "glosario", "preguntas-frecuentes", "herramientas", os.path.join("en", "guides"),
            os.path.join("en", "glossary"), os.path.join("en", "faq"), os.path.join("en", "tools")]:
    shutil.rmtree(os.path.join(ROOT, top), ignore_errors=True)
en_dir = os.path.join(ROOT, "en")
if os.path.isdir(en_dir) and not os.listdir(en_dir):
    os.rmdir(en_dir)

pages.sort()
block = "# BEGIN LIBRARY (generated by tools/flatten.py)\n" + "".join(
    f'[[redirects]]\n  from = "{u}"\n  to = "/{f}"\n  status = 200\n  force = true\n\n' for u, f in pages) + "# END LIBRARY"
toml_p = os.path.join(ROOT, "netlify.toml")
toml = open(toml_p, encoding="utf-8").read()
toml2 = re.sub(r"# BEGIN LIBRARY \(generated by tools/flatten.py\)\n.*?# END LIBRARY", lambda m: block, toml, flags=re.S)
if toml2 == toml and block not in toml:
    raise SystemExit("flatten: BEGIN/END LIBRARY markers not found in netlify.toml")
open(toml_p, "w", encoding="utf-8", newline="\n").write(toml2)
print(f"flattened {len(pages)} pages; netlify.toml library block: {len(pages)} rewrites (no 301s)")
